### ISSUE TITLE
Error: Cannot find module 'q'

### ISSUE THREAD

**Issue by jerrobertson** [diegogurgel/ramltomd#2]
I tried running this on a local project and got the following error/stacktrace:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\jerrobertson\AppData\Roaming\npm\node_modules\ramltomd\lib\ramltomd.js:7:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

This happens even when I don't specify any parameters

**Comment by diegogurgel** [comment]
@jerrobertson thanks for that. I add the 'q' module in the dependencies. Just update ramltomd module.
